Odiseo\Bundle\ChallengeBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
        videoUrl:
            column: video_url
            type: string
            length: 255 
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        challenges:
            targetEntity: Odiseo\Bundle\ChallengeBundle\Entity\User
            mappedBy: challengedBy
            
    manyToOne:
        challengedBy:
            targetEntity: Odiseo\Bundle\ChallengeBundle\Entity\User
            inversedBy: challenges
            joinColumn:
                name: challenged_by
                referencedColumnName: id
            
    lifecycleCallbacks: {  }