odiseo_challenge_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: OdiseoChallengeBundle:Backend/Main:dashboard }

odiseo_challenge_backend_user:
    resource: @OdiseoChallengeBundle/Resources/config/routing/backend/user.yml
    prefix: /users